
version: '3.9'
services:
  db:
    env_file: 
      - ./backend/.env
    image: postgres:latest
    networks:
      - default
    ports:
      - 5400:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: always

  
  server:
    depends_on: 
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: sh ./start.sh
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000

  client:
    depends_on:
      - server
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend/:/frontend/
      - '/frontend/node_modules'
      - '/frontend/dist'
    ports:
      - 3333:3333
    command: serve -s /frontend/dist -l 3333 
volumes: 
  postgres_data:
